### ISSUE TITLE
Invalid value null for configuration key serializer exception

### ISSUE THREAD

**Issue by rajeshdasi** [bakdata/kafka-large-message-serde#44]
I'm trying out this library with the sample code provided [here](https://medium.com/bakdata/processing-large-messages-with-kafka-streams-167a166ca38b) but I'm getting an exception.

Sample Code:
```
public class KafkaLargeMessageSerdeProcessor {

    public void processLargeMessageSerde(String filename, String topicName) throws IOException {

        final Properties props = new Properties();
        props.setProperty(StreamsConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
        props.setProperty(StreamsConfig.APPLICATION_ID_CONFIG, "s3-backed-serde-app");
        props.put(StreamsConfig.DEFAULT_KEY_SERDE_CLASS_CONFIG, Serdes.StringSerde.class);
        props.put(StreamsConfig.DEFAULT_VALUE_SERDE_CLASS_CONFIG, S3BackedSerde.class);
        props.setProperty(AbstractS3BackedConfig.BASE_PATH_CONFIG, "s3://large-blob-data-test/");
        props.put(S3BackedSerdeConfig.VALUE_SERDE_CLASS_CONFIG, Serdes.StringSerde.class);

        Producer<String, String> producer = new KafkaProducer<>(props);

        FileInputStream inputStream;
        try {
            inputStream = new FileInputStream(filename);
            byte[] buffer = new byte[1024 * 1024];
            int bytesRead;
            while ((bytesRead = inputStream.read(buffer)) != -1) {
                String chunk = new String(buffer, 0, bytesRead, StandardCharsets.UTF_8);
                ProducerRecord<String, String> record = new ProducerRecord<>(topicName, chunk);
                producer.send(record);
            }
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        try {
            producer.close();
            inputStream.close();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

    }
}
```

Error: 
```
Exception in thread "main" org.apache.kafka.common.config.ConfigException: Invalid value null for configuration key.serializer: must be non-null.
	at org.apache.kafka.clients.producer.ProducerConfig.appendSerializerToConfig(ProducerConfig.java:579)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:290)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:317)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:302)
	at com.example.KafkaLargeMessageSerdeProcessor.processLargeMessageSerde(KafkaLargeMessageSerdeProcessor.java:29)
	at com.example.Main.main(Main.java:14)
```

I just want to know what I'm missing here.

**Comment by philipp94831** [comment]
You are not configuring the producer correctly. You have to use
```
props.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, Serdes.StringSerde.class);
props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, S3BackedSerializer.class);
```

**Comment by philipp94831** [comment]
Oh sorry. You have to put StringSerializer. Nevertheless, these are questions unrelated to this project but rather general Kafka API usage so please refer to the respective docs

**Comment by rajeshdasi** [comment]
Can you share a complete working example to use this library? I want to push the file to s3 using this library and get the metadata where the file is stored.

**Comment by rajeshdasi** [comment]
Do we have any complete example for offloading the large message sent through Kafka to blob storage?

**Comment by philipp94831** [comment]
```
final Properties props = new Properties();
        props.setProperty(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
        props.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class);
        props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, LargeMessageSerializer.class);
        props.setProperty(AbstractLargeMessageConfig.BASE_PATH_CONFIG, "s3://large-blob-data-test/");
        props.put(LargeMessageSerdeConfig.VALUE_SERDE_CLASS_CONFIG, Serdes.StringSerde.class);

        try (final Producer<String, String> producer = new KafkaProducer<>(props)) {
            final ProducerRecord<String, String> record = new ProducerRecord<>("topic", "key", "value");
            producer.send(record);
            producer.flush();
        }
```

**Comment by philipp94831** [comment]
Please have a look at the README of this project.
> Make sure to also add [Confluent Maven Repository](http://packages.confluent.io/maven/) to your build file.

**Comment by rajeshdasi** [comment]
Thanks for your quick support @philipp94831.
